// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Dokumenti → Documents*
 */
export interface DokumentiDocumentDataDocumentsItem {
  /**
   * Document Title field in *Dokumenti → Documents*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dokumenti.documents[].document_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  document_title: prismic.KeyTextField;

  /**
   * Document Description field in *Dokumenti → Documents*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dokumenti.documents[].document_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  document_description: prismic.KeyTextField;

  /**
   * File field in *Dokumenti → Documents*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: dokumenti.documents[].file
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  file: prismic.LinkToMediaField;
}

type DokumentiDocumentDataSlicesSlice = never;

/**
 * Content for Dokumenti documents
 */
interface DokumentiDocumentData {
  /**
   * Heading field in *Dokumenti*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dokumenti.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Small Heading field in *Dokumenti*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dokumenti.small_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  small_heading: prismic.KeyTextField;

  /**
   * Overtitle field in *Dokumenti*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dokumenti.overtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  overtitle: prismic.KeyTextField;

  /**
   * Documents field in *Dokumenti*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: dokumenti.documents[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  documents: prismic.GroupField<Simplify<DokumentiDocumentDataDocumentsItem>>;

  /**
   * Slice Zone field in *Dokumenti*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: dokumenti.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DokumentiDocumentDataSlicesSlice> /**
   * Meta Title field in *Dokumenti*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: dokumenti.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Dokumenti*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: dokumenti.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Dokumenti*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: dokumenti.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Dokumenti document from Prismic
 *
 * - **API ID**: `dokumenti`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DokumentiDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DokumentiDocumentData>,
    "dokumenti",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | NajaveListSliceSlice
  | SectionHeadingSliceSlice
  | TekstSlikaSlice
  | HeroSliceSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type KontaktDocumentDataSlicesSlice = never;

/**
 * Content for Kontakt documents
 */
interface KontaktDocumentData {
  /**
   * Heading field in *Kontakt*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: kontakt.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Subheading field in *Kontakt*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: kontakt.subheading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * Slice Zone field in *Kontakt*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: kontakt.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<KontaktDocumentDataSlicesSlice> /**
   * Meta Title field in *Kontakt*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: kontakt.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Kontakt*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: kontakt.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Kontakt*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: kontakt.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Kontakt document from Prismic
 *
 * - **API ID**: `kontakt`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type KontaktDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<KontaktDocumentData>,
    "kontakt",
    Lang
  >;

type NajavaIliDogadanjeSingleDocumentDataSlicesSlice = never;

/**
 * Content for Najava ili događanje Single documents
 */
interface NajavaIliDogadanjeSingleDocumentData {
  /**
   * Heading field in *Najava ili događanje Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: najava_ili_dogadanje_single.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Image field in *Najava ili događanje Single*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: najava_ili_dogadanje_single.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Content field in *Najava ili događanje Single*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: najava_ili_dogadanje_single.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *Najava ili događanje Single*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: najava_ili_dogadanje_single.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NajavaIliDogadanjeSingleDocumentDataSlicesSlice> /**
   * Meta Title field in *Najava ili događanje Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: najava_ili_dogadanje_single.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Najava ili događanje Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: najava_ili_dogadanje_single.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Najava ili događanje Single*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: najava_ili_dogadanje_single.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Najava ili događanje Single document from Prismic
 *
 * - **API ID**: `najava_ili_dogadanje_single`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NajavaIliDogadanjeSingleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NajavaIliDogadanjeSingleDocumentData>,
    "najava_ili_dogadanje_single",
    Lang
  >;

type NajaveIDogadanjaDocumentDataSlicesSlice = never;

/**
 * Content for Najave i događanja documents
 */
interface NajaveIDogadanjaDocumentData {
  /**
   * Heading field in *Najave i događanja*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: najave_i_dogadanja.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Slice Zone field in *Najave i događanja*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: najave_i_dogadanja.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NajaveIDogadanjaDocumentDataSlicesSlice> /**
   * Meta Title field in *Najave i događanja*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: najave_i_dogadanja.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Najave i događanja*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: najave_i_dogadanja.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Najave i događanja*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: najave_i_dogadanja.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Najave i događanja document from Prismic
 *
 * - **API ID**: `najave_i_dogadanja`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NajaveIDogadanjaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NajaveIDogadanjaDocumentData>,
    "najave_i_dogadanja",
    Lang
  >;

export type AllDocumentTypes =
  | DokumentiDocument
  | HomepageDocument
  | KontaktDocument
  | NajavaIliDogadanjeSingleDocument
  | NajaveIDogadanjaDocument;

/**
 * Default variation for Heading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Heading*
 */
type HeadingSliceVariation = HeadingSliceDefault;

/**
 * Heading Shared Slice
 *
 * - **API ID**: `heading`
 * - **Description**: Heading
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadingSlice = prismic.SharedSlice<
  "heading",
  HeadingSliceVariation
>;

/**
 * Primary content in *HeroSlice → Default → Primary*
 */
export interface HeroSliceSliceDefaultPrimary {
  /**
   * Heading field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Subtitle field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * PrimaryButtonLabel field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.primaryButtonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  primaryButtonLabel: prismic.KeyTextField;

  /**
   * PrimaryButtonLink field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.primaryButtonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primaryButtonLink: prismic.LinkField;

  /**
   * SecondaryButtonLabel field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.secondaryButtonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondaryButtonLabel: prismic.KeyTextField;

  /**
   * SecondaryButtonLink field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.secondaryButtonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  secondaryButtonLink: prismic.LinkField;
}

/**
 * Default variation for HeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSlice*
 */
type HeroSliceSliceVariation = HeroSliceSliceDefault;

/**
 * HeroSlice Shared Slice
 *
 * - **API ID**: `hero_slice`
 * - **Description**: HeroSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSlice = prismic.SharedSlice<
  "hero_slice",
  HeroSliceSliceVariation
>;

/**
 * Primary content in *NajaveListSlice → Default → Primary*
 */
export interface NajaveListSliceSliceDefaultPrimary {
  /**
   * Heading field in *NajaveListSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: najave_list_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Overheading field in *NajaveListSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: najave_list_slice.default.primary.overheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  overheading: prismic.KeyTextField;
}

/**
 * Default variation for NajaveListSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NajaveListSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NajaveListSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NajaveListSlice*
 */
type NajaveListSliceSliceVariation = NajaveListSliceSliceDefault;

/**
 * NajaveListSlice Shared Slice
 *
 * - **API ID**: `najave_list_slice`
 * - **Description**: NajaveListSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NajaveListSliceSlice = prismic.SharedSlice<
  "najave_list_slice",
  NajaveListSliceSliceVariation
>;

/**
 * Primary content in *SectionHeadingSlice → Default → Primary*
 */
export interface SectionHeadingSliceSliceDefaultPrimary {
  /**
   * Heading field in *SectionHeadingSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_heading_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Subheading field in *SectionHeadingSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_heading_slice.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;
}

/**
 * Default variation for SectionHeadingSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionHeadingSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionHeadingSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SectionHeadingSlice*
 */
type SectionHeadingSliceSliceVariation = SectionHeadingSliceSliceDefault;

/**
 * SectionHeadingSlice Shared Slice
 *
 * - **API ID**: `section_heading_slice`
 * - **Description**: SectionHeadingSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionHeadingSliceSlice = prismic.SharedSlice<
  "section_heading_slice",
  SectionHeadingSliceSliceVariation
>;

/**
 * Primary content in *TekstSlikaSlice → Default → Primary*
 */
export interface TekstSlikaSliceDefaultPrimary {
  /**
   * Heading field in *TekstSlikaSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tekst_slika.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Image field in *TekstSlikaSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tekst_slika.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Content field in *TekstSlikaSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tekst_slika.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * Button Link field in *TekstSlikaSlice → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: tekst_slika.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Label field in *TekstSlikaSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tekst_slika.default.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;
}

/**
 * Default variation for TekstSlikaSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TekstSlikaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TekstSlikaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TekstSlikaSlice*
 */
type TekstSlikaSliceVariation = TekstSlikaSliceDefault;

/**
 * TekstSlikaSlice Shared Slice
 *
 * - **API ID**: `tekst_slika`
 * - **Description**: TekstSlika
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TekstSlikaSlice = prismic.SharedSlice<
  "tekst_slika",
  TekstSlikaSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      DokumentiDocument,
      DokumentiDocumentData,
      DokumentiDocumentDataDocumentsItem,
      DokumentiDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      KontaktDocument,
      KontaktDocumentData,
      KontaktDocumentDataSlicesSlice,
      NajavaIliDogadanjeSingleDocument,
      NajavaIliDogadanjeSingleDocumentData,
      NajavaIliDogadanjeSingleDocumentDataSlicesSlice,
      NajaveIDogadanjaDocument,
      NajaveIDogadanjaDocumentData,
      NajaveIDogadanjaDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeadingSlice,
      HeadingSliceVariation,
      HeadingSliceDefault,
      HeroSliceSlice,
      HeroSliceSliceDefaultPrimary,
      HeroSliceSliceVariation,
      HeroSliceSliceDefault,
      NajaveListSliceSlice,
      NajaveListSliceSliceDefaultPrimary,
      NajaveListSliceSliceVariation,
      NajaveListSliceSliceDefault,
      SectionHeadingSliceSlice,
      SectionHeadingSliceSliceDefaultPrimary,
      SectionHeadingSliceSliceVariation,
      SectionHeadingSliceSliceDefault,
      TekstSlikaSlice,
      TekstSlikaSliceDefaultPrimary,
      TekstSlikaSliceVariation,
      TekstSlikaSliceDefault,
    };
  }
}
