// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  heading: dynamic(() => import("./Heading")),
  hero_slice: dynamic(() => import("./HeroSlice")),
  najave_list_slice: dynamic(() => import("./NajaveListSlice")),
  section_heading_slice: dynamic(() => import("./SectionHeadingSlice")),
  tekst_slika: dynamic(() => import("./TekstSlikaSlice")),
};
